# roles/mariadb/tasks/install.yml
---

- name: Install MariaDB keys
  apt_key:
    keyserver: "{{ mariadb_apt_keyserver }}"
    id: "{{ mariadb_apt_keyid }}"
    state: present

- name: Add official MariaDB apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
    filename: mariadb
  register: mariadb_install_packages
  with_items: '{{mariadb_apt_repositories}}'

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
