# playbooks/roles/phpmyadmin/tasks/main.yml
---
- name: Download phpMyAdmin
  get_url:
    url: "{{ phpmyadmin_download_url }}"
    dest: "/tmp/phpmyadmin.tar.gz"
    mode: '0644'

- name: Create installation directory
  file:
    path: "{{ phpmyadmin_install_dir }}"
    state: directory
    mode: '0755'

- name: Extract phpMyAdmin
  unarchive:
    src: "/tmp/phpmyadmin.tar.gz"
    dest: "{{ phpmyadmin_install_dir }}"
    extra_opts: ["--strip-components=1"]
    remote_src: yes

- name: Check services
  service_facts:

- name: Template config file
  template:
    src: config.inc.php.j2
    dest: "{{ phpmyadmin_config_dir }}/config.inc.php"
    mode: '0644'

- name: Creating a virtual host
  template:
    src: phpmyadmin-apache.conf.j2
    dest: /etc/apache2/sites-available/phpmyadmin.conf
    mode: '0644'
  notify: Reload Apache
  when:
   - "'apache2.service' in ansible_facts.services"
   - ansible_facts.services['apache2.service'].status == 'enabled'

- name: Enable phpMyAdmin site (Apache)
  file:
    src: ../sites-available/phpmyadmin.conf
    dest: /etc/apache2/sites-enabled/phpmyadmin.conf
    state: link
  when:
   - "'apache2.service' in ansible_facts.services"
   - ansible_facts.services['apache2.service'].status == 'enabled'

- name: Copy Nginx configuration for phpMyAdmin
  template:
    src: phpmyadmin.conf.j2
    dest: /etc/nginx/sites-available/phpmyadmin.conf
  notify: Reload Nginx
  when:
   - "'nginx.service' in ansible_facts.services"
   - ansible_facts.services['nginx.service'].status == 'enabled'

- name: Enable phpMyAdmin site (Nginx)
  file:
    src: ../sites-available/phpmyadmin.conf
    dest: /etc/nginx/sites-enabled/phpmyadmin.conf
    state: link
  when:
   - "'nginx.service' in ansible_facts.services"
   - ansible_facts.services['nginx.service'].status == 'enabled'
