---
# Install PHP
- name: Install PHP {{php_version}} PPA Repository
  apt_repository:
    repo: 'ppa:ondrej/php'
  tags:
    - php

- name: Install PHP{{php_version}}
  apt:
    name: php{{php_version}}
    state: latest

- name: Mask Apache2 service(If PHP installed with Apache2)
  apt:
    name: apache2
    state: absent

- name: Install PHP and other php dependencies.
  apt:
    name:
      [
        "php{{php_version}}-dev",
        "php{{php_version}}-curl",
        "php{{php_version}}-fpm",
        "php{{php_version}}-gd",
        "php{{php_version}}-imap",
        "php{{php_version}}-bcmath",
        "php{{php_version}}-tokenizer",
        "php{{php_version}}-xml",
        "php{{php_version}}-intl",
        "php{{php_version}}-mbstring",
        "php{{php_version}}-pdo",
        "php{{php_version}}-mysql",
        "php{{php_version}}-xdebug",  # for debugging
        "composer",
      ]
    state: latest
    force: yes
    update_cache: yes

- name: Copy php.ini file
  template:
    src: php.ini.j2
    dest: "/etc/php/{{php_version}}/fpm/php.ini"
  notify: Restart php-fpm
