---
# Install Nginx
- name: Install Latest Nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes
  tags: install_nginx

- name: Remove default nginx vhost config file.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Create Nginx virtual host
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/{{ domain_name }}.conf
  notify: Reload Nginx

- name: Enable Newly added site
  file:
    src: "../sites-available/{{domain_name}}.conf"
    dest: "/etc/nginx/sites-enabled/{{domain_name}}.conf"
    state: link
  notify: Reload Nginx

- name: Ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    state: started
    enabled: yes
