- hosts: all
  vars:
    # System configuration
    system_remote_root: /vagrant/remote

    # Web server configuration
    #domain_name: example.com # if you want to use a domain name
    www_document_root: /var/www/remote/laravel-app/public # Laravel public directory

    # Server timezone
    timesync_timezone: Asia/Tokyo
    timesync_ntp_hosts:
      - ntp.nict.jp

    # PHP
    php_version: 8.4
    php_date_timezone: Asia/Tokyo
    php_mbstring_language: Japanese

    # MariaDB
    mariadb_version: 11.7
    mariadb_root_password: root

    # Laravel
    laravel_version: '11.*'
    laravel_project: /var/www/remote/laravel-app
    laravel_timezone: Asia/Tokyo
    laravel_locale: ja_JP

    # Database for development
    db_host: 'localhost'
    db_port: 3306
    db_name: 'my_database'
    db_user: 'my_user'
    db_password: 'my_password'
    mariadb_databases:
      - name: '{{ db_name }}'
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    mariadb_users:
      - name: '{{ db_user}}'
        password: '{{ db_password }}'
        priv: '{{ db_name }}.*:ALL'
        host: '{{ db_host}}'

  roles:
    - stuvusit.systemd-timesyncd
    - common
    - php
    - nginx
    - mariadb
    - phpmyadmin

  tasks:
    - name: Check if Laravel project directory exists
      stat:
        path: "{{ laravel_project }}"
      register: laravel_dir

    - name: Create temporary directory
      tempfile:
        state: directory
        suffix: _laravel_temp
      register: temp_dir
      when: not laravel_dir.stat.exists

    - name: Create Laravel project in temporary directory
      command: composer -q create-project 'laravel/laravel:{{ laravel_version }}' laravel-app
      args:
        chdir: "{{ temp_dir.path }}"
        creates: "{{ temp_dir.path }}/laravel-app"
      register: create_laravel_project
      when: not laravel_dir.stat.exists

    - name: Install language package
      command: composer require laravel-lang/common --dev
      args:
        chdir: "{{ temp_dir.path }}/laravel-app"
      when: not laravel_dir.stat.exists

    - name: Add Japanese language
      command: php artisan lang:add ja
      args:
        chdir: "{{ temp_dir.path }}/laravel-app"
      when: not laravel_dir.stat.exists

    - name: Set Japanese environment
      lineinfile:
        path: "{{ temp_dir.path }}/laravel-app/.env"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^APP_LOCALE=.*', line: 'APP_LOCALE=ja' }
        - { regexp: '^APP_FAKER_LOCALE=.*', line: 'APP_FAKER_LOCALE={{ laravel_locale }}' }
        - { regexp: '^APP_TIMEZONE=.*', line: 'APP_TIMEZONE={{ laravel_timezone }}' }
      when: not laravel_dir.stat.exists

    - name: Add database configuration to .env file
      lineinfile:
        path: "{{ temp_dir.path }}/laravel-app/.env"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?\s*DB_CONNECTION=.*', line: 'DB_CONNECTION=mysql' }
        - { regexp: '^#?\s*DB_HOST=.*',       line: 'DB_HOST={{ db_host }}' }
        - { regexp: '^#?\s*DB_PORT=.*',       line: 'DB_PORT={{ db_port }}' }
        - { regexp: '^#?\s*DB_DATABASE=.*',   line: 'DB_DATABASE={{ db_name }}' }
        - { regexp: '^#?\s*DB_USERNAME=.*',   line: 'DB_USERNAME={{ db_user }}' }
        - { regexp: '^#?\s*DB_PASSWORD=.*',   line: 'DB_PASSWORD={{ db_password }}' }
      when: not laravel_dir.stat.exists

    - name: Ensure target directory exists
      file:
        path: "{{ laravel_project | dirname }}"
        state: directory
        mode: '0755'
      when: not laravel_dir.stat.exists

    - name: Move Laravel project to final location
      command: mv "{{ temp_dir.path }}/laravel-app" "{{ laravel_project }}"
      args:
        creates: "{{ laravel_project }}"
      when: not laravel_dir.stat.exists

    - name: Clean up temporary directory
      file:
        path: "{{ temp_dir.path }}"
        state: absent
      when: not laravel_dir.stat.exists

    - name: Migrate database
      command: php artisan migrate
      args:
        chdir: "{{ laravel_project }}"
      when: not laravel_dir.stat.exists