- hosts: all
  vars:
    # System configuration
    system_remote_root: /vagrant/remote

    # Web server configuration
    #domain_name: example.com # if you want to use a domain name
    www_document_root: /var/www/remote/laravel-app/public # Laravel public directory

    # Server timezone
    timesync_timezone: Asia/Tokyo
    timesync_ntp_hosts:
      - ntp.nict.jp

    # PHP
    php_version: 8.4
    php_date_timezone: Asia/Tokyo
    php_mbstring_language: Japanese

    # MariaDB
    mariadb_version: 11.7
    mariadb_root_password: root

    # Laravel
    laravel_version: '11.*'
    laravel_project: /var/www/remote/laravel-app

    # Database for development
    db_host: 'localhost'
    db_port: 3306
    db_name: 'my_database'
    db_user: 'my_user'
    db_password: 'my_password'
    mariadb_databases:
      - name: '{{ db_name }}'
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    mariadb_users:
      - name: '{{ db_user}}'
        password: '{{ db_password }}'
        priv: '{{ db_name }}.*:ALL'
        host: '{{ db_host}}'

  roles:
    - stuvusit.systemd-timesyncd
    - common
    - php
    - nginx
    - mariadb
    - phpmyadmin

  tasks:
    - name: Create Laravel project
      shell: composer create-project 'laravel/laravel:{{ laravel_version }}' laravel-app
      args:
        chdir: /var/www/remote
        creates: /var/www/remote/laravel-app

    - name: Add database configuration to .env file
      shell: |
        sed -i 's/^\(DB_CONNECTION=.*\)$/#\1/' {{ laravel_project }}/.env
        sed -i 's/^\(DB_HOST=.*\)$/#\1/' {{ laravel_project }}/.env
        sed -i 's/^\(DB_PORT=.*\)$/#\1/' {{ laravel_project }}/.env
        sed -i 's/^\(DB_DATABASE=.*\)$/#\1/' {{ laravel_project }}/.env
        sed -i 's/^\(DB_USERNAME=.*\)$/#\1/' {{ laravel_project }}/.env
        sed -i 's/^\(DB_PASSWORD=.*\)$/#\1/' {{ laravel_project }}/.env
        echo "### Database configuration
        DB_CONNECTION=mysql
        DB_HOST={{ db_host }}
        DB_PORT={{ db_port }}
        DB_DATABASE={{ db_name }}
        DB_USERNAME={{ db_user }}
        DB_PASSWORD={{ db_password }}" >> {{ laravel_project }}/.env

    - name: Migrate database
      command: php artisan migrate
      args:
        chdir: '{{ laravel_project }}'