- hosts: all
  vars:
    # System configuration
    system_remote_root: /vagrant/remote

    # Web server configuration
    #domain_name: example.com # if you want to use a domain name
    www_document_root: /var/www/remote/laravel-app/public # Laravel public directory

    # Server timezone
    timesync_timezone: Asia/Tokyo
    timesync_ntp_hosts:
      - ntp.nict.jp

    # PHP
    php_version: 8.4
    php_date_timezone: Asia/Tokyo
    php_mbstring_language: Japanese

    # MariaDB
    mariadb_version: 11.7
    mariadb_root_password: root

    # Laravel
    laravel_version: '11.*'
    laravel_project: /var/www/remote/laravel-app
    laravel_timezone: Asia/Tokyo
    laravel_locale: ja_JP

    # Database for development
    db_host: 'localhost'
    db_port: 3306
    db_name: 'my_database'
    db_user: 'my_user'
    db_password: 'my_password'
    mariadb_databases:
      - name: '{{ db_name }}'
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    mariadb_users:
      - name: '{{ db_user}}'
        password: '{{ db_password }}'
        priv: '{{ db_name }}.*:ALL'
        host: '{{ db_host}}'

  roles:
    - stuvusit.systemd-timesyncd
    - common
    - php
    - nginx
    - mariadb
    - phpmyadmin

  tasks:
    - name: Create Laravel project
      #shell: composer create-project 'laravel/laravel:{{ laravel_version }}' laravel-app
      command: composer create-project 'laravel/laravel:{{ laravel_version }}' laravel-app
      args:
        chdir: /var/www/remote
        creates: '{{ laravel_project }}'
      register: create_laravel_project

    - name: Install language package
      command: composer require laravel-lang/common --dev
      args:
        chdir: '{{ laravel_project }}'
      when: create_laravel_project.changed

    - name: Add Japanese language
      command: php artisan lang:add ja
      args:
        chdir: '{{ laravel_project }}'
      when: create_laravel_project.changed

    - name: Set Japanese environment
      lineinfile:
        path: '{{ laravel_project }}/.env'
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - { regexp: '^APP_LOCALE=.*', line: 'APP_LOCALE=ja' }
        - { regexp: '^APP_FAKER_LOCALE=.*', line: 'APP_FAKER_LOCALE={{ laravel_locale }}' }
        - { regexp: '^APP_TIMEZONE=.*', line: 'APP_TIMEZONE={{ laravel_timezone }}' }

    - name: Add database configuration to .env file
      lineinfile:
        path: '{{ laravel_project }}/.env'
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - { regexp: '^#?\s*DB_CONNECTION=.*', line: 'DB_CONNECTION=mysql' }
        - { regexp: '^#?\s*DB_HOST=.*',       line: 'DB_HOST={{ db_host }}' }
        - { regexp: '^#?\s*DB_PORT=.*',       line: 'DB_PORT={{ db_port }}' }
        - { regexp: '^#?\s*DB_DATABASE=.*',   line: 'DB_DATABASE={{ db_name }}' }
        - { regexp: '^#?\s*DB_USERNAME=.*',   line: 'DB_USERNAME={{ db_user }}' }
        - { regexp: '^#?\s*DB_PASSWORD=.*',   line: 'DB_PASSWORD={{ db_password }}' }

    - name: Migrate database
      command: php artisan migrate
      args:
        chdir: '{{ laravel_project }}'